# Generated by Django 4.1 on 2023-01-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending_challenge', '0002_alter_spending_challenge_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending_challenge',
            name='budget',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
