# Generated by Django 4.1 on 2023-01-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
