# Generated by Django 4.1 on 2023-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_alter_spending_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
