# Generated by Django 4.1 on 2023-01-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0003_alter_spending_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='date',
            new_name='when',
        ),
    ]
