# Generated by Django 4.1 on 2023-01-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0004_rename_date_spending_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='when',
            field=models.DateField(),
        ),
    ]
