# Generated by Django 4.1.5 on 2023-01-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_memo_alter_income_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='purpose',
        ),
    ]
