# Generated by Django 4.1 on 2023-01-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_date_alter_income_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='when',
        ),
    ]
