# Generated by Django 4.1 on 2023-01-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_rename_date_income_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='when',
            field=models.DateField(),
        ),
    ]
